

module.exports = {
    CURRENCY: 'zł',
    LOGIN: 'Logowanie',
    PASSWORD: 'Hasło',
    SIGN_IN: "Zaloguj",
    SIGN_UP: 'Zarejestruj się',
    ACCEPT: 'Akceptuj',
    CANCEL: 'Anuluj',
    REPEAT_PASSWORD: "Powtórz hasło",
    BAD_CREDENTIALS: 'Zła nazwa użytkownika lub hasło',
    LOGIN_ERROR: 'Bład logowania',
    WRONG_EMAIL_FORMAT: 'Zły format adresu email',
    PASSWORD_DONT_MATCH: 'Podane hasła nie są takie same',
    USER_CANT_BE_EMPTY: 'Nazwa użytkownika nie może być pusta',
    PASSWORD_CANT_BE_EMPTY: 'Hasło nie może być puste',
    PRODUCT_CATEGORIES: 'Kategorie produktów',
    HOME_PAGE: 'Strona główna',
    ALL_CATEGORIES: "Wszystkie",
    QUANTITY_LABEL_NAMES: ["mała", "średnia", "duża", "b. duża"],
    SEARCH_PRODUCTS: "Wyszukaj produkty",
    SEARCH: 'Szukaj',
    ACTIVE: 'Aktywne',
    PRICE: "Cena",
    NAME: "Nazwa",
    AVAILABILITY: "Dostępność",
    QUANTITY: "Ilość",
    FIRST_LAST_NAME: 'Imię i nazwisko',
    SELLER: "Sprzedający",
    VILLAGE: "Miejscowość",
    HOME_NUMBER: 'Numer domu',
    PHONE: 'Numer telefonu',
    ADDRESS: "Adres",
    ACTIONS: "Akcje",
    CATEGORY: "Kategoria",
    UNIT: "Jednostka",
    RELATED_ITEMS: "Powiązane produkty",
    CALL: "Zadzwoń",
    PRODUCT_DESCRIPTION: "Opis",
    OFFER_TITLE_CANT_BE_EMPTY: 'tytuł nie może byc pusty',
    NEED_SELECT_CATEGORY: 'musisz wybrać kategorię produktu',
    NEED_PROVIDE_PRICE: 'musisz podać cenę produktu',
    WRONG_PRICE: 'podana cena jest nieprawidłowa',
    NEED_SELECT_UNIT: 'musisz wybrać jednostkę',
    NEED_PROVIDE_DESCRIPTION: 'musisz dodać opis',
    NEDD_PROVIDE_NAME_LASTNAME: 'musisz podać imię i nazwisko',
    NEED_SELECT_VILLAGE: 'musisz wybrać miejscowość',
    WRONG_PHONE_FORMATED: 'podany numer telefonu "%s" jest nieprawidłowy',
    DATA: 'Dane',
    PASS_ITEM_DETAILS_TEXT: 'Podaj informacje o produkcie wraz z jego opisem.',
    PHOTOS: 'Zdjęcia',
    IMAGE_UPLOADER_BUTTON_LABEL: 'Wybierz zdjęcie',
    IMAGE_UPLOADER_LABEL: 'Maksymalny rozmiar zdjęcia: 10MB',
    IMAGE_UPLOADER_WRONG_EXTENSION: 'Ten format zdjęć nie jest obsługiwany',
    UPLOADING: 'wysyłanie',
    UPLOAD_FAILED: 'błąd wysyłania',
    RECEIPT: 'Odbiór',
    RECEIPT_ADDRESS_DETAILS_TEXT: 'Podaj miejsce odbioru.',
    REMEMBER_ADDRESS_TEXT: 'Zapamiętaj dane odbioru.',
    ALERT_DIALOG_RETURN_BACK: 'Powrócić?',
    ALERT_DIALOG_ABANDON_CHANGES_TEXT: 'Wprowadzone zmiany nie zostaną zapisane. Czy chcesz kontynuować?',
    ALERT_DIALOG_DELETE_OFFER_TITLE: 'Usunięcie produktu',
    ALERT_DIALOG_DELETE_OFFER_TEXT: `Usunięcie produktu sprawi, że nie będzie ona więcej dostępna.
                                     Ta operacja jest nieodwracalna. Czy chcesz kontynuować?`,
    DEACTIVATE_OFFER_TEXT: `Tutaj możesz włączyć lub ukryć ogłoszenie.`,
    ADD_OFFER: 'Dodaj produkt',
    MY_OFFERS: 'Moje Produkty',
    POPULAR_PRODUCTS: 'Popularne produkty',
    CLICK_CHANGE_RANGE: 'kliknij aby zmienić zakres',
    FOUND: 'znaleziono',
    FOR: 'dla',
    SETTINGS: 'Ustawienia',
    LOGOUT: 'Wyloguj',
    CONTACT: 'Kontakt',
    INFO: 'Informacje',
    HELP: 'Pomoc',
    BACK: "Powrót",
    SAVE: "Zapisz",
    EDITION: "Edycja",
    PRIVACY_POLICY: 'Polityka prywatności',
    COOKIE_POLICY: 'Polityka cookie',
    COOKIE_MESSAGE: 'Ta strona wykorzystuje plikie cookie. Jeśli nie wyrażasz zgody, zmień ustawienia swojej przeglądarki.',
}
